---
- name: install pre-requisites
  apt:
    name: "{{ netdata_script_dependencies }}"
    state: present
    update_cache: true
  become: yes

- name: Install GPG Key from Netdata
  apt_key:
    url: https://packagecloud.io/netdata/netdata-edge/gpgkey
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: deb https://packagecloud.io/netdata/netdata-edge/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Add source repository
  apt_repository:
    repo: deb-src https://packagecloud.io/netdata/netdata-edge/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Install netdata
  apt:
    name: netdata=1.18.1182
    update_cache: true
  become: yes
