---
- name: Gather netdata version for each operating system version
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_version|int }}.yml"
    - main.yml

- name: Install Python apt bindings
  apt:
    pkg: "python3-apt"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Check installed packages"
  package_facts:
    manager: "auto"

- name: Check if installed netdata version differs
  set_fact:
    is_different_version: "{{ true if ansible_facts.packages['netdata'] is not defined else ansible_facts.packages['netdata'][0].version != netdata_version }}"
  changed_when: false

- name: install pre-requisites
  apt:
    pkg:
      - debian-archive-keyring
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Install GPG Key from Netdata
  apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: deb https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Add source repository
  apt_repository:
    repo: deb-src https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Unhold Netdata on this version
  dpkg_selections:
    name: netdata
    selection: install
  when: is_different_version

- name: Install netdata
  apt:
    name: "netdata={{ netdata_version }}"
    update_cache: true
  become: yes
  when: is_different_version
  notify:
    - Restart Netdata

- name: Hold Netdata on this version
  dpkg_selections:
    name: netdata
    selection: hold
  when: is_different_version

- name: Copy SSL certificate to netdata SSL folder
  template:
    src: "server_ssl_cert.pem.j2"
    dest: "/etc/netdata/ssl/cert.pem"
    owner: "netdata"
    group: "netdata"
    mode: 0600
  when: netdata_server_certificate is defined
  notify:
    - Restart Netdata
  become: yes

- name: Copy SSL key to netdata SSL folder
  template:
    src: "server_ssl_key.pem.j2"
    dest: "/etc/netdata/ssl/key.pem"
    owner: "netdata"
    group: "netdata"
    mode: 0600
  when: netdata_server_certificate_key is defined
  notify:
    - Restart Netdata
  become: yes

- name: Add Netdata user to Docker group
  user:
    name: "netdata"
    groups: "docker"
    append: "yes"
  when: ansible_facts.packages['docker-ce'] is defined or ansible_facts.packages['docker-ee'] is defined
  notify:
    - Restart Netdata
