---
- name: Gather netdata version for each operating system version
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}{{ ansible_distribution_version|int }}.yml"
    - main.yml

- include: libuv1_debian_8.yml
  when: ansible_os_family == "Debian" and ansible_distribution_version|int == 8

- name: install pre-requisites
  apt:
    pkg:
      - debian-archive-keyring
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true
  become: yes

- name: Install GPG Key from Netdata
  apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: deb https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Add source repository
  apt_repository:
    repo: deb-src https://packagecloud.io/netdata/netdata/{{ ansible_distribution | lower  }}/ {{ ansible_distribution_release }} main
    state: present
    filename: netdata
  become: yes

- name: Unhold Netdata on this version
  dpkg_selections:
    name: netdata
    selection: install

- name: Install netdata
  apt:
    name: "netdata={{ netdata_version }}"
    update_cache: true
  become: yes
  notify:
    - Restart Netdata

- name: Hold Netdata on this version
  dpkg_selections:
    name: netdata
    selection: hold

- name: Copy SSL certificate to netdata SSL folder
  template:
    src: "server_ssl_cert.pem.j2"
    dest: "/etc/netdata/ssl/cert.pem"
    owner: "netdata"
    group: "netdata"
    mode: 0600
  when: netdata_server_certificate is defined
  notify:
    - Restart Netdata
  become: yes

- name: Copy SSL key to netdata SSL folder
  template:
    src: "server_ssl_key.pem.j2"
    dest: "/etc/netdata/ssl/key.pem"
    owner: "netdata"
    group: "netdata"
    mode: 0600
  when: netdata_server_certificate_key is defined
  notify:
    - Restart Netdata
  become: yes

- name: "Check installed packages (for Docker)"
  package_facts:
    manager: "auto"

- name: Add Netdata user to Docker group
  user:
    name: "netdata"
    groups: "docker"
    append: "yes"
  when: ansible_facts.packages | select('search', 'docker') | list | count > 0
  notify:
    - Restart Netdata
